#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCT")]
	public partial class DataQLCTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDuDinh(DuDinh instance);
    partial void UpdateDuDinh(DuDinh instance);
    partial void DeleteDuDinh(DuDinh instance);
    partial void InsertGiaoDichDuDinh(GiaoDichDuDinh instance);
    partial void UpdateGiaoDichDuDinh(GiaoDichDuDinh instance);
    partial void DeleteGiaoDichDuDinh(GiaoDichDuDinh instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    #endregion
		
		public DataQLCTDataContext() : 
				base(global::DTO.Properties.Settings.Default.QLCTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLCTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLCTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLCTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLCTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DuDinh> DuDinhs
		{
			get
			{
				return this.GetTable<DuDinh>();
			}
		}
		
		public System.Data.Linq.Table<GiaoDichDuDinh> GiaoDichDuDinhs
		{
			get
			{
				return this.GetTable<GiaoDichDuDinh>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DuDinh")]
	public partial class DuDinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDuDinh;
		
		private string _MaNguoiDung;
		
		private string _TenDuDinh;
		
		private System.Nullable<int> _TienDuDinh;
		
		private System.Nullable<System.DateTime> _ThoiGianDuDinh;
		
		private EntitySet<GiaoDichDuDinh> _GiaoDichDuDinhs;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDuDinhChanging(string value);
    partial void OnMaDuDinhChanged();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnTenDuDinhChanging(string value);
    partial void OnTenDuDinhChanged();
    partial void OnTienDuDinhChanging(System.Nullable<int> value);
    partial void OnTienDuDinhChanged();
    partial void OnThoiGianDuDinhChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianDuDinhChanged();
    #endregion
		
		public DuDinh()
		{
			this._GiaoDichDuDinhs = new EntitySet<GiaoDichDuDinh>(new Action<GiaoDichDuDinh>(this.attach_GiaoDichDuDinhs), new Action<GiaoDichDuDinh>(this.detach_GiaoDichDuDinhs));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuDinh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDuDinh
		{
			get
			{
				return this._MaDuDinh;
			}
			set
			{
				if ((this._MaDuDinh != value))
				{
					this.OnMaDuDinhChanging(value);
					this.SendPropertyChanging();
					this._MaDuDinh = value;
					this.SendPropertyChanged("MaDuDinh");
					this.OnMaDuDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10)")]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuDinh", DbType="NVarChar(100)")]
		public string TenDuDinh
		{
			get
			{
				return this._TenDuDinh;
			}
			set
			{
				if ((this._TenDuDinh != value))
				{
					this.OnTenDuDinhChanging(value);
					this.SendPropertyChanging();
					this._TenDuDinh = value;
					this.SendPropertyChanged("TenDuDinh");
					this.OnTenDuDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDuDinh", DbType="Int")]
		public System.Nullable<int> TienDuDinh
		{
			get
			{
				return this._TienDuDinh;
			}
			set
			{
				if ((this._TienDuDinh != value))
				{
					this.OnTienDuDinhChanging(value);
					this.SendPropertyChanging();
					this._TienDuDinh = value;
					this.SendPropertyChanged("TienDuDinh");
					this.OnTienDuDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDuDinh", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianDuDinh
		{
			get
			{
				return this._ThoiGianDuDinh;
			}
			set
			{
				if ((this._ThoiGianDuDinh != value))
				{
					this.OnThoiGianDuDinhChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianDuDinh = value;
					this.SendPropertyChanged("ThoiGianDuDinh");
					this.OnThoiGianDuDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuDinh_GiaoDichDuDinh", Storage="_GiaoDichDuDinhs", ThisKey="MaDuDinh", OtherKey="MaDuDinh")]
		public EntitySet<GiaoDichDuDinh> GiaoDichDuDinhs
		{
			get
			{
				return this._GiaoDichDuDinhs;
			}
			set
			{
				this._GiaoDichDuDinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DuDinh", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.DuDinhs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.DuDinhs.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoDichDuDinhs(GiaoDichDuDinh entity)
		{
			this.SendPropertyChanging();
			entity.DuDinh = this;
		}
		
		private void detach_GiaoDichDuDinhs(GiaoDichDuDinh entity)
		{
			this.SendPropertyChanging();
			entity.DuDinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaoDichDuDinh")]
	public partial class GiaoDichDuDinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiaoDichDuDinh;
		
		private string _MaDuDinh;
		
		private string _MaSanPham;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _Gia;
		
		private EntityRef<DuDinh> _DuDinh;
		
		private EntityRef<SanPham> _SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiaoDichDuDinhChanging(string value);
    partial void OnMaGiaoDichDuDinhChanged();
    partial void OnMaDuDinhChanging(string value);
    partial void OnMaDuDinhChanged();
    partial void OnMaSanPhamChanging(string value);
    partial void OnMaSanPhamChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    #endregion
		
		public GiaoDichDuDinh()
		{
			this._DuDinh = default(EntityRef<DuDinh>);
			this._SanPham = default(EntityRef<SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaoDichDuDinh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiaoDichDuDinh
		{
			get
			{
				return this._MaGiaoDichDuDinh;
			}
			set
			{
				if ((this._MaGiaoDichDuDinh != value))
				{
					this.OnMaGiaoDichDuDinhChanging(value);
					this.SendPropertyChanging();
					this._MaGiaoDichDuDinh = value;
					this.SendPropertyChanged("MaGiaoDichDuDinh");
					this.OnMaGiaoDichDuDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuDinh", DbType="VarChar(10)")]
		public string MaDuDinh
		{
			get
			{
				return this._MaDuDinh;
			}
			set
			{
				if ((this._MaDuDinh != value))
				{
					if (this._DuDinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDuDinhChanging(value);
					this.SendPropertyChanging();
					this._MaDuDinh = value;
					this.SendPropertyChanged("MaDuDinh");
					this.OnMaDuDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="VarChar(10)")]
		public string MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuDinh_GiaoDichDuDinh", Storage="_DuDinh", ThisKey="MaDuDinh", OtherKey="MaDuDinh", IsForeignKey=true)]
		public DuDinh DuDinh
		{
			get
			{
				return this._DuDinh.Entity;
			}
			set
			{
				DuDinh previousValue = this._DuDinh.Entity;
				if (((previousValue != value) 
							|| (this._DuDinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuDinh.Entity = null;
						previousValue.GiaoDichDuDinhs.Remove(this);
					}
					this._DuDinh.Entity = value;
					if ((value != null))
					{
						value.GiaoDichDuDinhs.Add(this);
						this._MaDuDinh = value.MaDuDinh;
					}
					else
					{
						this._MaDuDinh = default(string);
					}
					this.SendPropertyChanged("DuDinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_GiaoDichDuDinh", Storage="_SanPham", ThisKey="MaSanPham", OtherKey="MaSanPham", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.GiaoDichDuDinhs.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.GiaoDichDuDinhs.Add(this);
						this._MaSanPham = value.MaSanPham;
					}
					else
					{
						this._MaSanPham = default(string);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDung;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private System.Nullable<int> _Tuoi;
		
		private EntitySet<DuDinh> _DuDinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnTuoiChanging(System.Nullable<int> value);
    partial void OnTuoiChanged();
    #endregion
		
		public NguoiDung()
		{
			this._DuDinhs = new EntitySet<DuDinh>(new Action<DuDinh>(this.attach_DuDinhs), new Action<DuDinh>(this.detach_DuDinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuoi", DbType="Int")]
		public System.Nullable<int> Tuoi
		{
			get
			{
				return this._Tuoi;
			}
			set
			{
				if ((this._Tuoi != value))
				{
					this.OnTuoiChanging(value);
					this.SendPropertyChanging();
					this._Tuoi = value;
					this.SendPropertyChanged("Tuoi");
					this.OnTuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DuDinh", Storage="_DuDinhs", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<DuDinh> DuDinhs
		{
			get
			{
				return this._DuDinhs;
			}
			set
			{
				this._DuDinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DuDinhs(DuDinh entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_DuDinhs(DuDinh entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSanPham;
		
		private string _TenSanPham;
		
		private EntitySet<GiaoDichDuDinh> _GiaoDichDuDinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSanPhamChanging(string value);
    partial void OnMaSanPhamChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    #endregion
		
		public SanPham()
		{
			this._GiaoDichDuDinhs = new EntitySet<GiaoDichDuDinh>(new Action<GiaoDichDuDinh>(this.attach_GiaoDichDuDinhs), new Action<GiaoDichDuDinh>(this.detach_GiaoDichDuDinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSanPham", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					this.OnMaSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaSanPham = value;
					this.SendPropertyChanged("MaSanPham");
					this.OnMaSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_GiaoDichDuDinh", Storage="_GiaoDichDuDinhs", ThisKey="MaSanPham", OtherKey="MaSanPham")]
		public EntitySet<GiaoDichDuDinh> GiaoDichDuDinhs
		{
			get
			{
				return this._GiaoDichDuDinhs;
			}
			set
			{
				this._GiaoDichDuDinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoDichDuDinhs(GiaoDichDuDinh entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_GiaoDichDuDinhs(GiaoDichDuDinh entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
	}
}
#pragma warning restore 1591
